import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { SignInButton, SignOutButton, SignUp, useUser } from "@clerk/nextjs";
import { RouterOutputs, api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";
import Loading from "~/components/loading";
import { useEffect, useState } from "react";
dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();
  const [input, setInput] = useState("");
  const ctx = api.useContext();
  const { mutate, isLoading: isPosting } = api.posts.create.useMutation({
    onSuccess: () => {
      setInput("");
      void ctx.posts.getAll.invalidate();
    },
  });

  if (!user) return null;
  return (
    <div className="flex w-full gap-3">
      <Image
        src={user.profileImageUrl}
        alt="profile image"
        className="h-16 w-16 rounded-full"
        width={56}
        height={56}
      />
      <input
        placeholder="type some emojis"
        className="grow bg-transparent text-white outline-none"
        value={input}
        type="text"
        onChange={(e) => setInput(e.target.value)}
        disabled={isPosting}
      />
      <button onClick={() => mutate({ content: input })}>Post</button>
    </div>
  );
};
type PostWithUser = RouterOutputs["posts"]["getAll"][number]; //!! import type, use instead of obnoxious typeof in typescript
const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div className="flex gap-3 border-b p-4" key={post.id}>
      <Image
        src={author.profilePicture}
        alt="profile image"
        className="h-16 w-16 rounded-full"
        width={56}
        height={56}
      />
      <div className="flex flex-col">
        <div className="flex text-slate-300">
          <span>{author.username}</span>
          <span>{`- ${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  );
};

const Feed = () => {
  const { data, isLoading: postsLoadeded } = api.posts.getAll.useQuery();
  if (!data) {
    return <Loading />;
  }
  return (
    <div>
      {data?.map((fullpost) => (
        <PostView {...fullpost} key={fullpost.post.id} />
      ))}
    </div>
  );
};

const Home: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  //fetch immediatly
  api.posts.getAll.useQuery();
  //return empty div if both arent loaded since user tends to load faster;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="color-white flex h-screen justify-center bg-black">
        <div className="w-full border-x md:max-w-2xl">
          <div className="flex border-b border-white p-4">
            <CreatePostWizard />
            {!isSignedIn && <SignInButton />}
            {isSignedIn && <SignOutButton />}
          </div>
          {isSignedIn && <Feed />}
        </div>
      </main>
    </>
  );
};

export default Home;
